apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret
spec:
  destination:
    name: in-cluster
    namespace: default
  project: default
  source:
    repoURL: https://github.com/Sahakanush/sops_secret.git
    path: Secrets
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
