apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-secret-main
spec:
  destination:
    name: in-cluster
    namespace: argo-cd
  project: default
  source:
    repoURL: https://github.com/Sahakanush/sops_secret.git
    path: Secrets
    targetRevision: HEAD
    helm:
        version: v3
        valueFiles:
          - secrets://https://raw.githubusercontent.com/Sahakanush/sops_secret/blob/main/Secrets/secrets-1.yaml #encrypted file path
          - secrets://https://raw.githubusercontent.com/Sahakanush/sops_secret/blob/main/Secrets/secrets-2.yaml #encrypted file path
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

