apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-secret-main
spec:
  destination:
    name: in-cluster
    namespace: argo-cd
  project: default
  source:
    repoURL: https://github.com/Sahakanush/sops_secret.git
    path: Secrets
    targetRevision: HEAD
    helm:
        values: "{{secret-1.yaml}}"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

