apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret-app
spec:
  destination:
    name: in-cluster
    namespace: argo-cd
  project: default
  source:
    repoURL: https://github.com/Sahakanush/sops_secret.git
    path: Secrets
    targetRevision: HEAD
    helm:
        valueFiles:
          - 'secrets+age-import:///helm-secrets-private-keys/key.txt?./templates/secrets.yaml'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

