apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-secret
spec:
  destination:
    namespace: argo-cd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/Sahakanush/sops_secret.git
    path: Secrets
    targetRevision: HEAD
    helm:
      valueFiles:
        - 'secrets+age-import:///helm-secrets-private-keys/key.txt?argocd-secrets-enc.yaml'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
