name: Slack Notification
on: push

jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: act10ns/slack@v1
      with: 
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          status: ${{ job.status }}
          channel: '#as'
          message: Deploying {{ env.GITHUB_REF_NAME }} branch
     
