name: Slack Notification
on: push

jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: slackapi/slack-github-action@v1.22.0
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      with:
        channel-id: '#as'
        status: ${{ job.status }}
        slack-message: "GitHub build result: ${{ job.status }}"
