name: Workflow2 

on:
  workflow_run:
    workflows: ["GitHub Actions Demo"]
    types:
      - completed
        
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉Its 2"
