apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: example-sopssecret
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: my-secret-name-1
          labels:
            label1: value1
          annotations:
            key1: value1
          stringData:
            data-name0: data-value0
          data:
            data-name1: ENC[AES256_GCM,data:N6aYsrJu3U925LGS9yUxZw==,iv:pnRJ7HNE10VOg5FrcaWz740bNHToGSEOiZsgSP0pojA=,tag:U3fwIvJBss2cEuah117ahg==,type:str]
        - name: jenkins-secret
          labels:
            jenkins.io/credentials-type: usernamePassword
          annotations:
            jenkins.io/credentials-description: credentials from Kubernetes
          stringData:
            username: myUsername
            password: Pa$$word
        - name: some-token
          stringData:
            token: Wb4ziZdELkdUf6m6KtNd7iRjjQRvSeJno5meH4NAGHFmpqJyEsekZ2WjX232s4Gj
        - name: docker-login
          type: kubernetes.io/dockerconfigjson
          stringData:
            .dockerconfigjson: '{"auths":{"index.docker.io":{"username":"imyuser","password":"mypass","email":"myuser@abc.com","auth":"aW15dXNlcjpteXBhc3M="}}}'
sops:
    kms:
        - arn: arn:aws:kms:eu-central-1:068737609226:key/3eff829b-6db9-4923-a468-76361b91a2fe
          created_at: "2022-09-16T10:30:51Z"
          enc: AQICAHgttuQIKxOf5Gk3UTkzIjwBiobrVbv+luKpBTco/SXCWAFvUVqsyEL0Yp8PlR7UWkSxAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMlMpXt+6QDxTeHfcHAgEQgDvYH106fIPE4sHeCyF4O5Lz4aOA9HqTp9p7GcvQ31VdJOEUrrCFRTh7eBIflcqR1g3RKcoScEFxJlORcg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-09-16T10:30:51Z"
    mac: ENC[AES256_GCM,data:/BUdGlLe5vXyTYwxaGAEcunIZzmOKKpRPOJv1q+MQcwLA9le0pXMfDKJF/l7JpV5zcQfTFPpk59NaOI9qN6T9xVbbmsRDBIIQdRnboKzZJQJTSlWT/dduqI9jMcCXuKM0d6WsbcQg6/ICzrf+iJ4iBI2Yp5kKZY890gybp8odPI=,iv:KZtmaN33aWz/0Q6/o/uoYgcjA9WZBbPDXqMMWxvDGLU=,tag:Xyr2qEA5bs5kLNVVetn0bw==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
