apiVersion: ENC[AES256_GCM,data:uVc=,iv:sY8tgtDNabJ4hh10pDyb0/rsUFoufM/pcMbVP1L0wgQ=,tag:toaMfX4psNwm77y0C4/8cA==,type:str]
data:
    .dockerconfigjson: ENC[AES256_GCM,data:RRAGhSZ6V6bWgEsHzmvBebGwzkXDYNtWiiNZNqJKfzXDAyGmqUmHjNVqJBbkur9kCoyNq7GMsFPbR9QjOmf/Zuvf1kix3R+Z9/aR6IgAmH0qKBuduWOe3NWgQ0cKOaxEQr6CswguFaat8Zn0vE8rrWt80c/VboN/0Y8Ob1LZ+bwMAyRBMFro0YMFkJiXFMngwXqACvNS4jR1pKyt,iv:ZjvvOyvKkFm0v0PiQESSzq419Ls+Cwvf/JnwyK+jqKg=,tag:OymGj4lZrUKRVo9+/IeD7A==,type:str]
kind: ENC[AES256_GCM,data:+yhDY54W,iv:Zy+ipZgj/Sy3XP/6OpwxZJ3XvUniPioWm9h+8ZANSeU=,tag:sFIKwWW1LOP4ipvKJT5J0A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:mnLdWSevbgIgxvztfvpIcTvnwh0=,iv:W94IeA5x6i5rHqcvBzonhEFtY5yraLROt+5mu5wl+no=,tag:Q44nQnr/Mzq6NkKZg4Wqtw==,type:str]
type: ENC[AES256_GCM,data:Rti2TUx/Hw2OEEhV9c5zCvn0nP8I3QsbMXwhWal3,iv:H4TbOD+KWkKi1nWVLQj2/3rehu7HyyDFO7IdJXkqGQ4=,tag:aATGwTmsYKxPs0URQRyMjg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kjrj9cc3v36p7hvjznffr8eqcn93gzl8tk4329knpku4nt4c5plqh7sm25
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwMUlJdXIyRmxjUlJLcitx
            TjJ5VEdmaTlYMFRzOXB1ZmE1aDRtU0JaVnk4ClZqWUdWZGI1U2oybDgvenZOazY1
            bkpNOXBTNmVtYkVWdUM5NEI4N1laNWsKLS0tIFJQTnZyQzA5MXFpZDJ1QzJNdlVY
            Ky9kYWE4OUhlenJLZW9rQkRHRDlWTmsKabtHfIIhq+x0bT720Cs8KVAIIx44K8gN
            MVmYh2+/0RlQa6JSsid1eYH4kL14cVts/p4E3H2YgxWiwcKkSdhamA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-29T12:25:48Z"
    mac: ENC[AES256_GCM,data:HBbYyLi28fxNg3g24fbzXg7A4gFJ6Htcmm/iDIbzG0rvl8nNQPkuQDyGQwiGj7bGJ6+ZiKb4ellpsWr7ygBq4pTmrChIOnLnXUxX5efESjbrz34rXVG1v4pMMjoKHk48QpPRaLn+Hb6eCqDPPHnQmz2SWvd2BKAaNYnrfCMSrZU=,iv:yORCbS4aiylCDwPAB46T7pJPCwk6wE8VOlXLJeqdF9M=,tag:co+O98sXcVpPsRFWSadHcQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
